# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-06-04 08:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('email', models.EmailField(max_length=255, unique=True, verbose_name='이메일')),
                ('username', models.CharField(max_length=30, verbose_name='닉네임')),
                ('permission', models.CharField(choices=[('AD', '관리자'), ('ET', '에디터'), ('MB', '일반')], default='MB', max_length=2, verbose_name='권한')),
                ('certification_date', models.DateField(blank=True, default=None, null=True, verbose_name='인증일')),
                ('is_certificated', models.BooleanField(default=False, verbose_name='인증여부')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
