# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-06-05 05:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='content',
            field=models.TextField(help_text='댓글 내용입니다.', verbose_name='내용'),
        ),
    ]
